[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

# tuigreet is a TUI greeter. The --cmd flag specifies what to run after login.
command = "tuigreet --cmd Hyprland"

# The user to run the command as. The greeter user must be in the 'video' group.
user = "greeter"
